import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { branchNameFor, filePathFor, normalizeRequest, renderYaml } from "./dns.js";
import { createProviderFromEnv } from "./git-provider.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const publicDir = path.resolve(__dirname, "../public");

const app = express();
const port = Number(process.env.PORT || 8080);
const baseBranch = process.env.GIT_BASE_BRANCH || "main";
const provider = createProviderFromEnv();

app.use(express.json());
app.use(express.static(publicDir));

function buildRequestArtifacts(payload) {
  const normalized = normalizeRequest(payload);
  const yaml = renderYaml(normalized);
  const filePath = filePathFor(normalized.subdomain);
  const branch = branchNameFor(normalized.subdomain);
  const title = `DNS: ${normalized.subdomain}.${normalized.zone} ${normalized.recordType}`;
  const body = [
    "## DNS Request",
    "",
    `- Host: ${normalized.subdomain}.${normalized.zone}`,
    `- Type: ${normalized.recordType}`,
    `- TTL: ${normalized.recordTTL}`,
    `- Targets: ${normalized.targets.join(", ")}`,
    `- Owner: ${normalized.owner}`,
    "",
    "Generated by dns-request-ui."
  ].join("\n");

  return { normalized, yaml, filePath, branch, title, body };
}

app.get("/api/health", (_req, res) => {
  res.json({ ok: true, provider: process.env.GIT_PROVIDER_MODE || "dry-run" });
});

app.post("/api/preview", (req, res) => {
  try {
    const artifacts = buildRequestArtifacts(req.body);
    res.json({
      filePath: artifacts.filePath,
      branch: artifacts.branch,
      title: artifacts.title,
      yaml: artifacts.yaml
    });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

app.post("/api/requests", async (req, res) => {
  try {
    const artifacts = buildRequestArtifacts(req.body);
    await provider.createBranch({ baseBranch, newBranch: artifacts.branch });
    await provider.upsertFile({
      branch: artifacts.branch,
      path: artifacts.filePath,
      content: artifacts.yaml,
      message: `Add DNS record for ${artifacts.normalized.subdomain}.${artifacts.normalized.zone}`
    });
    const pr = await provider.openPullRequest({
      branch: artifacts.branch,
      baseBranch,
      title: artifacts.title,
      body: artifacts.body
    });

    res.status(201).json({
      url: pr.url,
      branch: artifacts.branch,
      filePath: artifacts.filePath
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.listen(port, () => {
  process.stdout.write(`dns-request-ui listening on :${port}\n`);
});
