apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-request-ui
  namespace: dns-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns-request-ui
  template:
    metadata:
      labels:
        app: dns-request-ui
    spec:
      containers:
        - name: dns-request-ui
          image: ghcr.io/simardeep1792/dns-request-ui:af5cfb75a88b3d8dc306f24c9261e2f9ae8eb5b3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GIT_PROVIDER_MODE
              value: github
            - name: GIT_BASE_BRANCH
              value: main
            - name: GITHUB_REPO_OWNER
              value: simardeep1792
            - name: GITHUB_REPO_NAME
              value: dns-as-a-pr
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dns-request-ui-secrets
                  key: github-token
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
