apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dns-ui-simardeep-xyz
  namespace: dns
  annotations:
    simardeep.xyz/source-repository: "https://dev.azure.com/EDIP-PIDE/dns-as-a-pr/_git/dns-as-a-pr"
    simardeep.xyz/zone-scope: "simardeep-xyz"
  labels:
    simardeep.xyz/controlled-by: "dns-as-a-pr"
    simardeep.xyz/project-name: "dns-request-ui"
    simardeep.xyz/project-id: "edip-aurora-fgc"
    simardeep.xyz/owner: "platform"
spec:
  endpoints:
    - dnsName: dns-ui.simardeep.xyz
      recordType: A
      recordTTL: 300
      targets:
        - 35.244.224.153
