apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: test-simardeep-xyz
  namespace: dns
  annotations:
    simardeep.xyz/source-repository: "https://dev.azure.com/EDIP-PIDE/dns-as-a-pr/_git/dns-as-a-pr"
    simardeep.xyz/zone-scope: "simardeep-xyz"
  labels:
    simardeep.xyz/controlled-by: "dns-as-a-pr"
    simardeep.xyz/project-name: "dns-platform"
    simardeep.xyz/project-id: "edip-aurora-fgc"
    simardeep.xyz/owner: "platform-test"
spec:
  endpoints:
    - dnsName: test.simardeep.xyz
      recordType: TXT
      recordTTL: 300
      targets:
        # TXT record payloads are quoted at the DNS layer; keep quotes explicit.
        - '"dns-as-pr-works"'
