apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.6/cert-manager.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --issuer-ambient-credentials=true
          - --leader-election-namespace=cert-manager

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --leader-election-namespace=cert-manager

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: cert-manager:leaderelection
      namespace: kube-system
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cert-manager

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: cert-manager-cainjector:leaderelection
      namespace: kube-system
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cert-manager

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cert-manager:leaderelection
      namespace: kube-system
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cert-manager

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cert-manager-cainjector:leaderelection
      namespace: kube-system
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cert-manager

  - target:
      version: v1
      kind: ServiceAccount
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: external-dns@edip-aurora-fgc.iam.gserviceaccount.com
