apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-records
  namespace: argocd
  annotations:
    # Apply DNSEndpoint resources after ExternalDNS installs the CRD.
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://dev.azure.com/EDIP-PIDE/dns-as-a-pr/_git/dns-as-a-pr
    targetRevision: main
    path: dns-records
  destination:
    server: https://kubernetes.default.svc
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
